import type { Property } from "./types";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "prop_cesar_001",
    name: "Cesar Hills Apartments",
    address: "1234 Ascot Hills Dr",
    city: "Los Angeles",
    state: "CA",
    unitsTotal: 24,
    unitsOccupied: 22,
    unitsVacant: 2,
    type: "Multifamily",
    status: "active",
    createdAt: "2024-10-01",
  },
  {
    id: "prop_cesar_002",
    name: "Sunset View Duplex",
    address: "502 N Figueroa St",
    city: "Los Angeles",
    state: "CA",
    unitsTotal: 2,
    unitsOccupied: 2,
    unitsVacant: 0,
    type: "Single Family",
    status: "active",
    createdAt: "2024-09-12",
  },
  {
    id: "prop_cesar_003",
    name: "Cesar's Palace Offices",
    address: "900 Huntington Dr",
    city: "Alhambra",
    state: "CA",
    unitsTotal: 12,
    unitsOccupied: 9,
    unitsVacant: 3,
    type: "Commercial",
    status: "active",
    createdAt: "2024-08-05",
  },
  {
    id: "prop_cesar_004",
    name: "Cesar Short-Stay Lofts",
    address: "77 Downtown Way",
    city: "Los Angeles",
    state: "CA",
    unitsTotal: 10,
    unitsOccupied: 7,
    unitsVacant: 3,
    type: "Short-Term",
    status: "draft",
    createdAt: "2024-11-20",
  },
];
